# Generated by Django 5.1.3 on 2024-11-08 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('approver', models.CharField(max_length=100)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.process')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.processcode')),
            ],
        ),
    ]
