# Generated by Django 5.1.3 on 2024-11-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approvallevel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallevel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
