# Generated by Django 5.1.3 on 2024-11-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallevel',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.approver'),
        ),
    ]
